# Generated by Django 3.2.16 on 2022-11-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mahsulot',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
