# Generated by Django 3.2.16 on 2022-11-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_mahsulot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'postlarst', 'verbose_name_plural': 'postlar'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='mahsulot',
        ),
        migrations.AddField(
            model_name='post',
            name='daromadi',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
