# Generated by Django 3.2.16 on 2022-11-19 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221119_0747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'posttt', 'verbose_name_plural': 'postlar'},
        ),
    ]
